# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stamp', models.DateTimeField(verbose_name='Date')),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ph', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conductivity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flow_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('turbidity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
